- name: Build and Push Docker Image
  hosts: ansible_host
  gather_facts: false

  tasks:
  - name: Build Docker Image
    command: docker image build -t hys0254/mywebapp .
  - name: Login to Docker Hub
    command: docker login
  - name: Push Image to Docker Hub
    command: docker push hys0254/mywebapp
  - name: Remove Local Image
    command: docker image rm hys0254/mywebapp tomcat:9-jdk11


